name: Docker Image CI

on:
  release: 
    types: [published]
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and Push the Docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/github-workflow-test:latest
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
